### ISSUE TITLE
Support multiple entities

### ISSUE THREAD

**Issue by AndyVRD** [AnthonMS/my-cards#21]
Hi,

Any chance you can add support for multiple entities?

**Comment by AnthonMS** [comment]
I might be able to add this in the new my-slider-v2 card. 

I promise nothing since I have never seen the need for this. You can just put them in a vertical stack card and problem solved. I know, it's more copy pasting yaml, but less work for me. Hehe.

Note for self: Do this by checking if entities exist instead of entity, if it does, then it should simply loop through each entity and create a my-slider-v2 element with the same config but different entities. (It should not pass down evaluated config)
