### ISSUE TITLE
[Bug]: my-cards v2 not publised in hacs

### ISSUE THREAD

**Issue by vlaraort** [AnthonMS/my-cards#39]
### Current Behavior

Currently, if I try to update my-cards from HACS, the latest version available is 1.2, which doesn't contain the v2 version of the slider

### Expected Behavior

have a versio with the v2 slider

### Environment

```markdown
- OS: HA Docker
- Node:
- Version:
- Hassio:
```

**Comment by AnthonMS** [comment]
That's because HACS is broken.

HACS hasn't worked for me at all for over a year and I have gone back to manually installing and updating the custom cards I use.
It's not just this card I can't update through HACS, it's all my custom cards. I can't even update HACS. And I just don't have the time or energy to debug something like that at the moment. I'm sorry.

**Comment by AnthonMS** [comment]
I thought the Slider-v2 was in the HACS release. 

The latest release definitely contain Slider-v2.
